import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Download } from 'lucide-react';

const fields = [['module_title', 'Название модуля *'], ['module_description', 'Описание модуля'], ['lesson_title', 'Название урока *'], ['lesson_content', 'Текст урока'], ['assignment', 'Задание'], ['lesson_attachment', 'Файл урока'], ['assignment_attachment', 'Файл задания'], ['module_poster', 'Постер модуля']];
const getRows = (output) => Array.isArray(output) ? output : output?.rows || output?.data || [];

export default function LearningImport({ course, onDone }) {
  const [rows, setRows] = useState([]); const [headers, setHeaders] = useState([]); const [mapping, setMapping] = useState({}); const [files, setFiles] = useState({}); const [summary, setSummary] = useState(null); const [loading, setLoading] = useState(false);
  const uploadWorkbook = async (event) => { const file = event.target.files?.[0]; if (!file) return; setLoading(true); const { file_uri } = await base44.integrations.Core.UploadPrivateFile({ file }); const { signed_url } = await base44.integrations.Core.CreateFileSignedUrl({ file_uri }); const response = await base44.functions.invoke('parseLessonWorkbook', { file_url: signed_url }); const { headers: parsedHeaders, rows: parsedRows } = response.data; const autoMapping = {}; fields.forEach(([key, label]) => { const match = parsedHeaders.find((h) => h === label); if (match) autoMapping[key] = match; }); setRows(parsedRows); setHeaders(parsedHeaders); setMapping(autoMapping); setLoading(false); };
  const uploadFiles = async (event) => { const selected = [...(event.target.files || [])]; setLoading(true); const uploaded = await Promise.all(selected.map(async (file) => [file.name, (await base44.integrations.Core.UploadPrivateFile({ file })).file_uri])); setFiles({ ...files, ...Object.fromEntries(uploaded) }); setLoading(false); };
  const callImport = async (preview) => { setLoading(true); const response = await base44.functions.invoke('importLearningWorkbook', { courseId: course.id, rows, mapping, fileUris: files, preview }); setSummary(response.data); setLoading(false); if (!preview) onDone(); };
  if (!course) return <p className="text-sm text-muted-foreground">Сначала выберите курс.</p>;
  return <div className="space-y-4"><p className="text-sm text-muted-foreground">Загрузите .xlsx, сопоставьте столбцы и при необходимости добавьте файлы, имена которых указаны в таблице.</p><a href="/functions/generateLessonTemplate" download="lesson_template.xlsx"><Button type="button" variant="outline" className="w-full"><Download className="w-4 h-4 mr-2" />Скачать образец Excel (.xlsx)</Button></a><Input accept=".xlsx" type="file" onChange={uploadWorkbook} disabled={loading} />{rows.length > 0 && <><Input multiple type="file" onChange={uploadFiles} disabled={loading} /><p className="text-sm text-muted-foreground">Строк: {rows.length}. Загружено вложений: {Object.keys(files).length}.</p><div className="space-y-2">{fields.map(([key, label]) => <label className="block text-sm" key={key}><span className="text-foreground">{label}</span><select className="mt-1 flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={mapping[key] || ''} onChange={(e) => setMapping({ ...mapping, [key]: e.target.value })}><option value="">Не импортировать</option>{headers.map((header) => <option key={header} value={header}>{header}</option>)}</select></label>)}</div><div className="overflow-x-auto rounded-lg border border-border p-3 text-sm"><p className="font-medium mb-2">Предпросмотр</p>{rows.slice(0, 3).map((row, index) => <p className="whitespace-nowrap" key={index}>{index + 1}. {JSON.stringify(row)}</p>)}</div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={loading || !mapping.module_title || !mapping.lesson_title} onClick={() => callImport(true)}>Проверить совпадения</Button><Button type="button" disabled={loading || !mapping.module_title || !mapping.lesson_title} onClick={() => callImport(false)}>{loading ? 'Обработка…' : 'Импортировать'}</Button></div></>}{summary && <div className="rounded-lg bg-muted p-3 text-sm text-foreground">{summary.error || (summary.createdModules !== undefined ? `Модули: +${summary.createdModules}, обновлено ${summary.updatedModules}. Уроки: +${summary.createdLessons}, обновлено ${summary.updatedLessons}. Пропущено строк: ${summary.skipped}.` : `Готово к импорту: ${summary.valid}. Совпадений: модулей ${summary.existingModules}, уроков ${summary.existingLessons}. Пропущено: ${summary.skipped}.`)}</div>}</div>;
}