import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

export default function ModuleLessonForm({ modules, onCreateModule, onCreateLesson, saving }) {
  const [module, setModule] = useState({ title: '', description: '' });
  const [lesson, setLesson] = useState({ module_id: '', title: '', content: '', video_url: '', resource_url: '', practice_prompt: '', quiz_question: '', quiz_options: '', quiz_correct_index: '0' });
  const reset = () => setLesson({ module_id: '', title: '', content: '', video_url: '', resource_url: '', practice_prompt: '', quiz_question: '', quiz_options: '', quiz_correct_index: '0' });
  const submitLesson = (e) => { e.preventDefault(); const options = lesson.quiz_options.split('\n').map((item) => item.trim()).filter(Boolean); const quiz_questions = lesson.quiz_question && options.length > 1 ? [{ question: lesson.quiz_question, options, correct_index: Number(lesson.quiz_correct_index) }] : []; const { quiz_question, quiz_options, quiz_correct_index, ...data } = lesson; onCreateLesson({ ...data, quiz_questions }); reset(); };
  return <div className="space-y-6">
    <form className="space-y-3" onSubmit={(e) => { e.preventDefault(); onCreateModule(module); setModule({ title: '', description: '' }); }}><div className="font-medium text-foreground">Новый модуль</div><Input placeholder="Название модуля" required value={module.title} onChange={(e) => setModule({ ...module, title: e.target.value })} /><Textarea placeholder="Краткое описание" value={module.description} onChange={(e) => setModule({ ...module, description: e.target.value })} /><Button variant="outline" disabled={saving}>Добавить модуль</Button></form>
    {modules.length > 0 && <form className="space-y-3 border-t border-border pt-5" onSubmit={submitLesson}><div className="font-medium text-foreground">Новый урок</div><select required value={lesson.module_id} onChange={(e) => setLesson({ ...lesson, module_id: e.target.value })} className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Выберите модуль</option>{modules.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select><Input placeholder="Название урока" required value={lesson.title} onChange={(e) => setLesson({ ...lesson, title: e.target.value })} /><Textarea placeholder="Текст урока" required value={lesson.content} onChange={(e) => setLesson({ ...lesson, content: e.target.value })} /><Input placeholder="Ссылка на видео" type="url" value={lesson.video_url} onChange={(e) => setLesson({ ...lesson, video_url: e.target.value })} /><Input placeholder="Ссылка на материал" type="url" value={lesson.resource_url} onChange={(e) => setLesson({ ...lesson, resource_url: e.target.value })} /><Textarea placeholder="Практическое задание" value={lesson.practice_prompt} onChange={(e) => setLesson({ ...lesson, practice_prompt: e.target.value })} /><div className="border-t border-border pt-3 space-y-2"><div className="text-sm font-medium text-foreground">Проверочный вопрос, необязательно</div><Input placeholder="Вопрос" value={lesson.quiz_question} onChange={(e) => setLesson({ ...lesson, quiz_question: e.target.value })} /><Textarea placeholder="Варианты ответов, по одному в строке" value={lesson.quiz_options} onChange={(e) => setLesson({ ...lesson, quiz_options: e.target.value })} /><Input type="number" min="0" placeholder="Номер правильного варианта, начиная с 0" value={lesson.quiz_correct_index} onChange={(e) => setLesson({ ...lesson, quiz_correct_index: e.target.value })} /></div><Button variant="outline" disabled={saving}>Добавить урок</Button></form>}
  </div>;
}